
begin tran

INSERT INTO journal.ExerciseFocus (FocusDesc, ExerciseGroupId) VALUES ('Rear Deltoid',4)
INSERT INTO journal.ExerciseFocus (FocusDesc, ExerciseGroupId) VALUES ('Front Deltoid',4)
INSERT INTO journal.ExerciseFocus (FocusDesc, ExerciseGroupId) VALUES ('Side Deltoid',4)
INSERT INTO journal.ExerciseFocus (FocusDesc, ExerciseGroupId) VALUES ('Upper Back',1)
INSERT INTO journal.ExerciseFocus (FocusDesc, ExerciseGroupId) VALUES ('Traps',1)
INSERT INTO journal.ExerciseFocus (FocusDesc, ExerciseGroupId) VALUES ('Lower Back',1)
INSERT INTO journal.ExerciseFocus (FocusDesc, ExerciseGroupId) VALUES ('Lats',1)
INSERT INTO journal.ExerciseFocus (FocusDesc, ExerciseGroupId) VALUES ('Tricepts',6)
INSERT INTO journal.ExerciseFocus (FocusDesc, ExerciseGroupId) VALUES ('Biceps',6)
INSERT INTO journal.ExerciseFocus (FocusDesc, ExerciseGroupId) VALUES ('Forearm',6)
INSERT INTO journal.ExerciseFocus (FocusDesc, ExerciseGroupId) VALUES ('Hamstring',3)
INSERT INTO journal.ExerciseFocus (FocusDesc, ExerciseGroupId) VALUES ('Quads',3)
INSERT INTO journal.ExerciseFocus (FocusDesc, ExerciseGroupId) VALUES ('Calves',3)
INSERT INTO journal.ExerciseFocus (FocusDesc, ExerciseGroupId) VALUES ('Glutious Maximus',3)
INSERT INTO journal.ExerciseFocus (FocusDesc, ExerciseGroupId) VALUES ('Upper Chest',2)
INSERT INTO journal.ExerciseFocus (FocusDesc, ExerciseGroupId) VALUES ('Lower Chest',2)
INSERT INTO journal.ExerciseFocus (FocusDesc, ExerciseGroupId) VALUES ('Outer Chest',2)
INSERT INTO journal.ExerciseFocus (FocusDesc, ExerciseGroupId) VALUES ('Chest All',2)
INSERT INTO journal.ExerciseFocus (FocusDesc, ExerciseGroupId) VALUES ('Inner Chest',2)


INSERT INTO [journal].[ExerciseGroup] (GroupShortDesc, GroupLongDesc) VALUES ('Back', NULL)
INSERT INTO [journal].[ExerciseGroup] (GroupShortDesc, GroupLongDesc) VALUES ('Chest', NULL)
INSERT INTO [journal].[ExerciseGroup] (GroupShortDesc, GroupLongDesc) VALUES ('Legs', NULL)
INSERT INTO [journal].[ExerciseGroup] (GroupShortDesc, GroupLongDesc) VALUES ('Shoulders', NULL)
INSERT INTO [journal].[ExerciseGroup] (GroupShortDesc, GroupLongDesc) VALUES ('Spin', NULL)
INSERT INTO [journal].[ExerciseGroup] (GroupShortDesc, GroupLongDesc) VALUES ('Arms', NULL)


INSERT INTO [journal].[ExerciseLookUp] (ExerciseShortDesc, ExerciseLongDesc, ExerciseFocusId, IsMachine, MachineBrandName, IsPerSide) VALUES ('Bent Over Reverse Fly','Dumbbel Seated Bent Over Reverse Fly',1,0,NULL,1)
INSERT INTO [journal].[ExerciseLookUp] (ExerciseShortDesc, ExerciseLongDesc, ExerciseFocusId, IsMachine, MachineBrandName, IsPerSide) VALUES ('Standing Dumbbell Side Lateral',NULL,3,0,NULL,1)
INSERT INTO [journal].[ExerciseLookUp] (ExerciseShortDesc, ExerciseLongDesc, ExerciseFocusId, IsMachine, MachineBrandName, IsPerSide) VALUES ('Standing Dumbbell Upright Row',NULL,3,0,NULL,1)
INSERT INTO [journal].[ExerciseLookUp] (ExerciseShortDesc, ExerciseLongDesc, ExerciseFocusId, IsMachine, MachineBrandName, IsPerSide) VALUES ('Shoulder Press',NULL,2,1,'Life Fitness',0)
INSERT INTO [journal].[ExerciseLookUp] (ExerciseShortDesc, ExerciseLongDesc, ExerciseFocusId, IsMachine, MachineBrandName, IsPerSide) VALUES ('Rear Delt',NULL,1,1,'Life Fitness',0)
INSERT INTO [journal].[ExerciseLookUp] (ExerciseShortDesc, ExerciseLongDesc, ExerciseFocusId, IsMachine, MachineBrandName, IsPerSide) VALUES ('Lateral Raise',NULL,3,1,'Nautilus - Nitro',0)
INSERT INTO [journal].[ExerciseLookUp] (ExerciseShortDesc, ExerciseLongDesc, ExerciseFocusId, IsMachine, MachineBrandName, IsPerSide) VALUES ('Overhead Press',NULL,2,1,'Nautilus - Nitro',0)
INSERT INTO [journal].[ExerciseLookUp] (ExerciseShortDesc, ExerciseLongDesc, ExerciseFocusId, IsMachine, MachineBrandName, IsPerSide) VALUES ('Rear Deltoid',NULL,1,1,'Star Trac',0)
INSERT INTO [journal].[ExerciseLookUp] (ExerciseShortDesc, ExerciseLongDesc, ExerciseFocusId, IsMachine, MachineBrandName, IsPerSide) VALUES ('Lat Pull Down Cable',NULL,7,1,'General',0)
INSERT INTO [journal].[ExerciseLookUp] (ExerciseShortDesc, ExerciseLongDesc, ExerciseFocusId, IsMachine, MachineBrandName, IsPerSide) VALUES ('Seated Row Cable',NULL,6,1,'General',0)
INSERT INTO [journal].[ExerciseLookUp] (ExerciseShortDesc, ExerciseLongDesc, ExerciseFocusId, IsMachine, MachineBrandName, IsPerSide) VALUES ('Iso Lateral High Row',NULL,4,1,'Hammer Strength',1)
INSERT INTO [journal].[ExerciseLookUp] (ExerciseShortDesc, ExerciseLongDesc, ExerciseFocusId, IsMachine, MachineBrandName, IsPerSide) VALUES ('Iso Lateral Low Row',NULL,6,1,'Hammer Strength',1)
INSERT INTO [journal].[ExerciseLookUp] (ExerciseShortDesc, ExerciseLongDesc, ExerciseFocusId, IsMachine, MachineBrandName, IsPerSide) VALUES ('Pull Over',NULL,7,1,'Hammer Strength',0)
INSERT INTO [journal].[ExerciseLookUp] (ExerciseShortDesc, ExerciseLongDesc, ExerciseFocusId, IsMachine, MachineBrandName, IsPerSide) VALUES ('One Arm Dumbbell Rows - Bench',NULL,6,0,NULL,1)
INSERT INTO [journal].[ExerciseLookUp] (ExerciseShortDesc, ExerciseLongDesc, ExerciseFocusId, IsMachine, MachineBrandName, IsPerSide) VALUES ('Pull Ups',NULL,4,0,NULL,0)
INSERT INTO [journal].[ExerciseLookUp] (ExerciseShortDesc, ExerciseLongDesc, ExerciseFocusId, IsMachine, MachineBrandName, IsPerSide) VALUES ('Seated Row',NULL,6,1,'Life Fitness',0)
INSERT INTO [journal].[ExerciseLookUp] (ExerciseShortDesc, ExerciseLongDesc, ExerciseFocusId, IsMachine, MachineBrandName, IsPerSide) VALUES ('Pull Over',NULL,7,1,'Nautilus - Nitro',0)
INSERT INTO [journal].[ExerciseLookUp] (ExerciseShortDesc, ExerciseLongDesc, ExerciseFocusId, IsMachine, MachineBrandName, IsPerSide) VALUES ('Lat Pulldown',NULL,7,1,'Life Fitness',0)
INSERT INTO [journal].[ExerciseLookUp] (ExerciseShortDesc, ExerciseLongDesc, ExerciseFocusId, IsMachine, MachineBrandName, IsPerSide) VALUES ('Bent Over Row Dumbbell',NULL,6,0,NULL,1)
INSERT INTO [journal].[ExerciseLookUp] (ExerciseShortDesc, ExerciseLongDesc, ExerciseFocusId, IsMachine, MachineBrandName, IsPerSide) VALUES ('Fixed Pulldown',NULL,4,1,'Life Fitness',0)
INSERT INTO [journal].[ExerciseLookUp] (ExerciseShortDesc, ExerciseLongDesc, ExerciseFocusId, IsMachine, MachineBrandName, IsPerSide) VALUES ('Vertical Chest',NULL,18,1,'Nautilus - Xplod',1)
INSERT INTO [journal].[ExerciseLookUp] (ExerciseShortDesc, ExerciseLongDesc, ExerciseFocusId, IsMachine, MachineBrandName, IsPerSide) VALUES ('Iso Lateral Incline Press',NULL,15,1,'Hammer Strength',1)
INSERT INTO [journal].[ExerciseLookUp] (ExerciseShortDesc, ExerciseLongDesc, ExerciseFocusId, IsMachine, MachineBrandName, IsPerSide) VALUES ('Deltoid Pec Fly',NULL,19,1,'Star Trac',0)
INSERT INTO [journal].[ExerciseLookUp] (ExerciseShortDesc, ExerciseLongDesc, ExerciseFocusId, IsMachine, MachineBrandName, IsPerSide) VALUES ('Incline Press',NULL,15,1,'Nautilus - Nitro',0)
INSERT INTO [journal].[ExerciseLookUp] (ExerciseShortDesc, ExerciseLongDesc, ExerciseFocusId, IsMachine, MachineBrandName, IsPerSide) VALUES ('Vartical Chest',NULL,18,1,'Nautilus - Nitro',0)
INSERT INTO [journal].[ExerciseLookUp] (ExerciseShortDesc, ExerciseLongDesc, ExerciseFocusId, IsMachine, MachineBrandName, IsPerSide) VALUES ('Pectoid Fly',NULL,19,1,'Life Fitness',0)
INSERT INTO [journal].[ExerciseLookUp] (ExerciseShortDesc, ExerciseLongDesc, ExerciseFocusId, IsMachine, MachineBrandName, IsPerSide) VALUES ('Seated Leg Press Machine',NULL,14,1,'Life Fitness',0)
INSERT INTO [journal].[ExerciseLookUp] (ExerciseShortDesc, ExerciseLongDesc, ExerciseFocusId, IsMachine, MachineBrandName, IsPerSide) VALUES ('Seated Leg Curl',NULL,11,1,'Life Fitness',0)
INSERT INTO [journal].[ExerciseLookUp] (ExerciseShortDesc, ExerciseLongDesc, ExerciseFocusId, IsMachine, MachineBrandName, IsPerSide) VALUES ('Seated Leg Curl',NULL,11,1,'Nautilus',0)
INSERT INTO [journal].[ExerciseLookUp] (ExerciseShortDesc, ExerciseLongDesc, ExerciseFocusId, IsMachine, MachineBrandName, IsPerSide) VALUES ('Leg Extensions',NULL,12,1,'Nautilus - Nitro',0)
INSERT INTO [journal].[ExerciseLookUp] (ExerciseShortDesc, ExerciseLongDesc, ExerciseFocusId, IsMachine, MachineBrandName, IsPerSide) VALUES ('Leg Extensions',NULL,12,1,'Life Fitness',0)
INSERT INTO [journal].[ExerciseLookUp] (ExerciseShortDesc, ExerciseLongDesc, ExerciseFocusId, IsMachine, MachineBrandName, IsPerSide) VALUES ('V Squat',NULL,14,1,'Hammer Strength',1)
INSERT INTO [journal].[ExerciseLookUp] (ExerciseShortDesc, ExerciseLongDesc, ExerciseFocusId, IsMachine, MachineBrandName, IsPerSide) VALUES ('Leg Extensions',NULL,12,1,'Star Trac',1)
INSERT INTO [journal].[ExerciseLookUp] (ExerciseShortDesc, ExerciseLongDesc, ExerciseFocusId, IsMachine, MachineBrandName, IsPerSide) VALUES ('Leg Press',NULL,12,1,'Star Trac',0)
INSERT INTO [journal].[ExerciseLookUp] (ExerciseShortDesc, ExerciseLongDesc, ExerciseFocusId, IsMachine, MachineBrandName, IsPerSide) VALUES ('Hack Squat',NULL,12,1,'TBD',1)


INSERT INTO [journal].[TrainingLocation] (TrainingLocationSId, LocationShortDesc, LocationLongDesc) VALUES ('LATroy', 'LA - Troy', NULL)
INSERT INTO [journal].[TrainingLocation] (TrainingLocationSId, LocationShortDesc, LocationLongDesc) VALUES ('LAWarren', 'LA - Warren', NULL)
INSERT INTO [journal].[TrainingLocation] (TrainingLocationSId, LocationShortDesc, LocationLongDesc) VALUES ('UWMPont', 'UWM - Pontiac', NULL)
INSERT INTO [journal].[TrainingLocation] (TrainingLocationSId, LocationShortDesc, LocationLongDesc) VALUES ('UWMTroy', 'UWM - Troy', NULL)


INSERT INTO [journal].[TrainingLogDetails] (TrainingLogId, ExerciseId, ExerciseSetOrder, WeightResistence, Repetitions, Comments) VALUES (1, 1, 1, 15.00, 18, null)
INSERT INTO [journal].[TrainingLogDetails] (TrainingLogId, ExerciseId, ExerciseSetOrder, WeightResistence, Repetitions, Comments) VALUES (1, 1, 2, 20.00, 13, null)
INSERT INTO [journal].[TrainingLogDetails] (TrainingLogId, ExerciseId, ExerciseSetOrder, WeightResistence, Repetitions, Comments) VALUES (1, 1, 3, 25.00, 12, null)
INSERT INTO [journal].[TrainingLogDetails] (TrainingLogId, ExerciseId, ExerciseSetOrder, WeightResistence, Repetitions, Comments) VALUES (1, 1, 4, 20.00, 13, null)
INSERT INTO [journal].[TrainingLogDetails] (TrainingLogId, ExerciseId, ExerciseSetOrder, WeightResistence, Repetitions, Comments) VALUES (1, 2, 1, 15.00, 15, null)
INSERT INTO [journal].[TrainingLogDetails] (TrainingLogId, ExerciseId, ExerciseSetOrder, WeightResistence, Repetitions, Comments) VALUES (1, 2, 2, 20.00, 14, null)
INSERT INTO [journal].[TrainingLogDetails] (TrainingLogId, ExerciseId, ExerciseSetOrder, WeightResistence, Repetitions, Comments) VALUES (1, 2, 3, 25.00, 8, null)
INSERT INTO [journal].[TrainingLogDetails] (TrainingLogId, ExerciseId, ExerciseSetOrder, WeightResistence, Repetitions, Comments) VALUES (1, 2, 4, 20.00, 13, null)
INSERT INTO [journal].[TrainingLogDetails] (TrainingLogId, ExerciseId, ExerciseSetOrder, WeightResistence, Repetitions, Comments) VALUES (1, 2, 5, 20.00, 99, 'Burning down starting at 20 lb')
INSERT INTO [journal].[TrainingLogDetails] (TrainingLogId, ExerciseId, ExerciseSetOrder, WeightResistence, Repetitions, Comments) VALUES (1, 4, 1, 110.00, 13, null)
INSERT INTO [journal].[TrainingLogDetails] (TrainingLogId, ExerciseId, ExerciseSetOrder, WeightResistence, Repetitions, Comments) VALUES (1, 4, 2, 115.00, 13, null)
INSERT INTO [journal].[TrainingLogDetails] (TrainingLogId, ExerciseId, ExerciseSetOrder, WeightResistence, Repetitions, Comments) VALUES (1, 4, 3, 115.00, 11, null)
INSERT INTO [journal].[TrainingLogDetails] (TrainingLogId, ExerciseId, ExerciseSetOrder, WeightResistence, Repetitions, Comments) VALUES (1, 4, 4, 95.00, 10, null)
INSERT INTO [journal].[TrainingLogDetails] (TrainingLogId, ExerciseId, ExerciseSetOrder, WeightResistence, Repetitions, Comments) VALUES (1, 3, 1, 10.00, 18, null)
INSERT INTO [journal].[TrainingLogDetails] (TrainingLogId, ExerciseId, ExerciseSetOrder, WeightResistence, Repetitions, Comments) VALUES (1, 3, 2, 15.00, 15, null)
INSERT INTO [journal].[TrainingLogDetails] (TrainingLogId, ExerciseId, ExerciseSetOrder, WeightResistence, Repetitions, Comments) VALUES (1, 3, 3, 20.00, 13, null)
INSERT INTO [journal].[TrainingLogDetails] (TrainingLogId, ExerciseId, ExerciseSetOrder, WeightResistence, Repetitions, Comments) VALUES (2, 1, 1, 20.00, 20, NULL)
INSERT INTO [journal].[TrainingLogDetails] (TrainingLogId, ExerciseId, ExerciseSetOrder, WeightResistence, Repetitions, Comments) VALUES (2, 1, 2, 25.00, 16, NULL)
INSERT INTO [journal].[TrainingLogDetails] (TrainingLogId, ExerciseId, ExerciseSetOrder, WeightResistence, Repetitions, Comments) VALUES (2, 1, 3, 25.00, 11, NULL)
INSERT INTO [journal].[TrainingLogDetails] (TrainingLogId, ExerciseId, ExerciseSetOrder, WeightResistence, Repetitions, Comments) VALUES (2, 1, 4, 20.00, 13, NULL)
INSERT INTO [journal].[TrainingLogDetails] (TrainingLogId, ExerciseId, ExerciseSetOrder, WeightResistence, Repetitions, Comments) VALUES (2, 1, 5, 10.00, 0, '4 sec')
INSERT INTO [journal].[TrainingLogDetails] (TrainingLogId, ExerciseId, ExerciseSetOrder, WeightResistence, Repetitions, Comments) VALUES (2, 2, 1, 20.00, 20, NULL)
INSERT INTO [journal].[TrainingLogDetails] (TrainingLogId, ExerciseId, ExerciseSetOrder, WeightResistence, Repetitions, Comments) VALUES (2, 2, 2, 20.00, 15, NULL)
INSERT INTO [journal].[TrainingLogDetails] (TrainingLogId, ExerciseId, ExerciseSetOrder, WeightResistence, Repetitions, Comments) VALUES (2, 2, 3, 25.00, 8, NULL)
INSERT INTO [journal].[TrainingLogDetails] (TrainingLogId, ExerciseId, ExerciseSetOrder, WeightResistence, Repetitions, Comments) VALUES (2, 2, 4, 25.00, 6, NULL)
INSERT INTO [journal].[TrainingLogDetails] (TrainingLogId, ExerciseId, ExerciseSetOrder, WeightResistence, Repetitions, Comments) VALUES (2, 2, 5, 20.00, 0, 'burn down starting @ 20lb')
INSERT INTO [journal].[TrainingLogDetails] (TrainingLogId, ExerciseId, ExerciseSetOrder, WeightResistence, Repetitions, Comments) VALUES (2, 4, 1, 115.00, 11, NULL)
INSERT INTO [journal].[TrainingLogDetails] (TrainingLogId, ExerciseId, ExerciseSetOrder, WeightResistence, Repetitions, Comments) VALUES (2, 4, 2, 115.00, 12, NULL)
INSERT INTO [journal].[TrainingLogDetails] (TrainingLogId, ExerciseId, ExerciseSetOrder, WeightResistence, Repetitions, Comments) VALUES (2, 4, 3, 130.00, 6, NULL)
INSERT INTO [journal].[TrainingLogDetails] (TrainingLogId, ExerciseId, ExerciseSetOrder, WeightResistence, Repetitions, Comments) VALUES (2, 3, 1, 10.00, 18, NULL)
INSERT INTO [journal].[TrainingLogDetails] (TrainingLogId, ExerciseId, ExerciseSetOrder, WeightResistence, Repetitions, Comments) VALUES (2, 3, 2, 20.00, 17, NULL)
INSERT INTO [journal].[TrainingLogDetails] (TrainingLogId, ExerciseId, ExerciseSetOrder, WeightResistence, Repetitions, Comments) VALUES (2, 3, 3, 20.00, 13, NULL)
INSERT INTO [journal].[TrainingLogDetails] (TrainingLogId, ExerciseId, ExerciseSetOrder, WeightResistence, Repetitions, Comments) VALUES (3, 1, 1, 25.00, 18, NULL)
INSERT INTO [journal].[TrainingLogDetails] (TrainingLogId, ExerciseId, ExerciseSetOrder, WeightResistence, Repetitions, Comments) VALUES (3, 1, 2, 25.00, 15, NULL)
INSERT INTO [journal].[TrainingLogDetails] (TrainingLogId, ExerciseId, ExerciseSetOrder, WeightResistence, Repetitions, Comments) VALUES (3, 1, 3, 25.00, 13, NULL)
INSERT INTO [journal].[TrainingLogDetails] (TrainingLogId, ExerciseId, ExerciseSetOrder, WeightResistence, Repetitions, Comments) VALUES (3, 1, 4, 15.00, 15, NULL)
INSERT INTO [journal].[TrainingLogDetails] (TrainingLogId, ExerciseId, ExerciseSetOrder, WeightResistence, Repetitions, Comments) VALUES (3, 1, 5, 10.00, NULL, '4 sec')
INSERT INTO [journal].[TrainingLogDetails] (TrainingLogId, ExerciseId, ExerciseSetOrder, WeightResistence, Repetitions, Comments) VALUES (3, 2, 1, 20.00, 22, NULL)
INSERT INTO [journal].[TrainingLogDetails] (TrainingLogId, ExerciseId, ExerciseSetOrder, WeightResistence, Repetitions, Comments) VALUES (3, 2, 2, 20.00, 16, NULL)
INSERT INTO [journal].[TrainingLogDetails] (TrainingLogId, ExerciseId, ExerciseSetOrder, WeightResistence, Repetitions, Comments) VALUES (3, 2, 3, 20.00, 13, 'going for less rest more flex & focus but xplod')
INSERT INTO [journal].[TrainingLogDetails] (TrainingLogId, ExerciseId, ExerciseSetOrder, WeightResistence, Repetitions, Comments) VALUES (3, 2, 4, 20.00, 13, 'going for less rest more flex & focus but xplod')
INSERT INTO [journal].[TrainingLogDetails] (TrainingLogId, ExerciseId, ExerciseSetOrder, WeightResistence, Repetitions, Comments) VALUES (3, 2, 5, 15.00, NULL, 'burn down starting @15lb')
INSERT INTO [journal].[TrainingLogDetails] (TrainingLogId, ExerciseId, ExerciseSetOrder, WeightResistence, Repetitions, Comments) VALUES (3, 4, 1, 80.00, 13, NULL)
INSERT INTO [journal].[TrainingLogDetails] (TrainingLogId, ExerciseId, ExerciseSetOrder, WeightResistence, Repetitions, Comments) VALUES (3, 4, 2, 80.00, 13, NULL)
INSERT INTO [journal].[TrainingLogDetails] (TrainingLogId, ExerciseId, ExerciseSetOrder, WeightResistence, Repetitions, Comments) VALUES (3, 4, 3, 80.00, 13, NULL)
INSERT INTO [journal].[TrainingLogDetails] (TrainingLogId, ExerciseId, ExerciseSetOrder, WeightResistence, Repetitions, Comments) VALUES (3, 4, 4, 80.00, 13, NULL)
INSERT INTO [journal].[TrainingLogDetails] (TrainingLogId, ExerciseId, ExerciseSetOrder, WeightResistence, Repetitions, Comments) VALUES (3, 3, 1, 10.00, 18, NULL)
INSERT INTO [journal].[TrainingLogDetails] (TrainingLogId, ExerciseId, ExerciseSetOrder, WeightResistence, Repetitions, Comments) VALUES (3, 3, 2, 10.00, 18, NULL)
INSERT INTO [journal].[TrainingLogDetails] (TrainingLogId, ExerciseId, ExerciseSetOrder, WeightResistence, Repetitions, Comments) VALUES (4, 5, 1, 85.00, 13, NULL)
INSERT INTO [journal].[TrainingLogDetails] (TrainingLogId, ExerciseId, ExerciseSetOrder, WeightResistence, Repetitions, Comments) VALUES (4, 5, 2, 100.00, 15, NULL)
INSERT INTO [journal].[TrainingLogDetails] (TrainingLogId, ExerciseId, ExerciseSetOrder, WeightResistence, Repetitions, Comments) VALUES (4, 5, 3, 115.00, 13, NULL)
INSERT INTO [journal].[TrainingLogDetails] (TrainingLogId, ExerciseId, ExerciseSetOrder, WeightResistence, Repetitions, Comments) VALUES (4, 5, 4, 120.00, 13, NULL)
INSERT INTO [journal].[TrainingLogDetails] (TrainingLogId, ExerciseId, ExerciseSetOrder, WeightResistence, Repetitions, Comments) VALUES (4, 2, 1, 20.00, 23, 'less rest btwn sets')
INSERT INTO [journal].[TrainingLogDetails] (TrainingLogId, ExerciseId, ExerciseSetOrder, WeightResistence, Repetitions, Comments) VALUES (4, 2, 2, 20.00, 24, NULL)
INSERT INTO [journal].[TrainingLogDetails] (TrainingLogId, ExerciseId, ExerciseSetOrder, WeightResistence, Repetitions, Comments) VALUES (4, 2, 3, 20.00, 20, NULL)
INSERT INTO [journal].[TrainingLogDetails] (TrainingLogId, ExerciseId, ExerciseSetOrder, WeightResistence, Repetitions, Comments) VALUES (4, 2, 4, 20.00, 13, NULL)
INSERT INTO [journal].[TrainingLogDetails] (TrainingLogId, ExerciseId, ExerciseSetOrder, WeightResistence, Repetitions, Comments) VALUES (4, 2, 5, 15.00, NULL, 'burndown start @15lb')
INSERT INTO [journal].[TrainingLogDetails] (TrainingLogId, ExerciseId, ExerciseSetOrder, WeightResistence, Repetitions, Comments) VALUES (4, 3, 1, 20.00, 17, NULL)


INSERT INTO [journal].[TrainingLogExerciseOrder] (TrainingLogid, TrainingLogOrder, exerciseId, comments) VALUES (1, 1, 1, NULL)
INSERT INTO [journal].[TrainingLogExerciseOrder] (TrainingLogid, TrainingLogOrder, exerciseId, comments) VALUES (1, 2, 2, NULL)
INSERT INTO [journal].[TrainingLogExerciseOrder] (TrainingLogid, TrainingLogOrder, exerciseId, comments) VALUES (1, 3, 4, NULL)
INSERT INTO [journal].[TrainingLogExerciseOrder] (TrainingLogid, TrainingLogOrder, exerciseId, comments) VALUES (1, 4, 3, NULL)
INSERT INTO [journal].[TrainingLogExerciseOrder] (TrainingLogid, TrainingLogOrder, exerciseId, comments) VALUES (2, 1, 1, NULL)
INSERT INTO [journal].[TrainingLogExerciseOrder] (TrainingLogid, TrainingLogOrder, exerciseId, comments) VALUES (2, 2, 2, NULL)
INSERT INTO [journal].[TrainingLogExerciseOrder] (TrainingLogid, TrainingLogOrder, exerciseId, comments) VALUES (2, 3, 4, NULL)
INSERT INTO [journal].[TrainingLogExerciseOrder] (TrainingLogid, TrainingLogOrder, exerciseId, comments) VALUES (2, 4, 3, NULL)
INSERT INTO [journal].[TrainingLogExerciseOrder] (TrainingLogid, TrainingLogOrder, exerciseId, comments) VALUES (3, 1, 1, NULL)
INSERT INTO [journal].[TrainingLogExerciseOrder] (TrainingLogid, TrainingLogOrder, exerciseId, comments) VALUES (3, 2, 2, NULL)
INSERT INTO [journal].[TrainingLogExerciseOrder] (TrainingLogid, TrainingLogOrder, exerciseId, comments) VALUES (3, 3, 4, NULL)
INSERT INTO [journal].[TrainingLogExerciseOrder] (TrainingLogid, TrainingLogOrder, exerciseId, comments) VALUES (3, 4, 3, NULL)
INSERT INTO [journal].[TrainingLogExerciseOrder] (TrainingLogid, TrainingLogOrder, exerciseId, comments) VALUES (4, 1, 5, NULL)
INSERT INTO [journal].[TrainingLogExerciseOrder] (TrainingLogid, TrainingLogOrder, exerciseId, comments) VALUES (4, 2, 2, NULL)
INSERT INTO [journal].[TrainingLogExerciseOrder] (TrainingLogid, TrainingLogOrder, exerciseId, comments) VALUES (4, 3, 3, NULL)